### ISSUE TITLE
Failed to install plugin 'js' for Gauge

### ISSUE THREAD

**Issue by manukulk** [getgauge/gauge-js#616] opened 2023-11-07 23:17 UTC
JS plugin installation is failing for Gauge 1.5.6

Steps to reproduce

Install Gauge 1.5.6 on windows using windows installer 
Select java, js and python plugins during installation 

-  All plugins got installed except JavaScript(js).
-  Tried to install js plugin manually by running the command **gauge install js** 
- Tried offline installation as well by running the command **gauge install --file gauge-js-4.0.0.zip**
- Tried installing various versions of js supported by Gauge (https://github.com/getgauge/gauge-js/releases)

**Logs**
All the above scenarios its failing with the error message
**[Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/js?l=&p=dotnet,html-report,java,ruby&o=windows&a=amd64
[Gauge] [DEBUG] Downloading https://github.com/getgauge/gauge-js/releases/download/v4.0.0/gauge-js-4.0.0.zip
[Gauge] [DEBUG] Running plugin hook command => [npm install --omit=dev --silent]
[Gauge] [ERROR] Failed to install plugin 'js' version 4.0.0.**
```
**Versions:**
 $ node -v
v20.9.0

$ npm -v
10.1.0

$ gauge -v
Gauge version: 1.5.6
Commit Hash: 9b96118

Plugins
-------
dotnet (0.5.2)
html-report (4.2.0)
java (0.10.3)
python (0.4.1)
ruby (0.7.1)
spectacle (0.1.4)
xml-report (0.4.0)

**Comment by chadlwilson** [comment] 2023-11-08 04:52
I believe there should be a debug log with the cache folder (`npm config get cache`), either `npm-debug.log` or one of the log files in `_logs`. Can you look for that and see what went wrong?

**Comment by manukulk** [comment] 2023-11-08 16:32
> I believe there should be a debug log within the cache folder (`npm config get cache`), either `npm-debug.log` or one of the log files in `_logs`. Can you look for that and see what went wrong?

I do not see any logs in that path when i run gauge commands. However i see these general logs
`0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.1.0
2 info using node@v20.9.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\<User>\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\NextGEN\repos\GaugeTest\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\<User>\.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\<User>\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 11ms
17 timing npm:load:configload Completed in 11ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm config get cache
22 verbose argv "config" "get" "cache"
23 timing npm:load:setTitle Completed in 0ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:C:\Users\<User>\AppData\Local\npm-cache\_logs\2023-11-08T06_50_59_911Z-
26 verbose logfile C:\Users\<User>\AppData\Local\npm-cache\_logs\2023-11-08T06_50_59_911Z-debug-0.log
27 timing npm:load:logFile Completed in 24ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 76ms
31 timing command:config Completed in 2ms
32 verbose exit 0
33 timing npm Completed in 179ms
34 info ok
`

**Comment by chadlwilson** [comment] 2023-11-08 19:16
Well, there's nothing anyone can do without logs. The assumption is that the npm install is failing for some reason on your machine, likely due to something in your environment.

Alternatively you can find the plugin directory within `~/.gauge/plugins` and try and manually run the plugin hook command it mentions above without the `--silent` to see what is happening.

**Comment by chadlwilson** [comment] 2023-12-11 03:41
Closing for now, as there's no additional information to help us debug or reproduce. Will re-open if you can find some additional information to help here.

**Closed by chadlwilson** 2023-12-11 03:41 UTC
