### ISSUE TITLE
indexOutOfRange in .gauge/plugins/js/2.3.6/node_modules/protobufjs/src/reader.js:94 

### ISSUE THREAD

**Issue by kramvan1** [getgauge/gauge-js#299] opened 2020-02-04 22:48 UTC
```
Feb 04 22:02:02 /root/.gauge/plugins/js/2.3.7/node_modules/protobufjs/src/reader.js:94
Feb 04 22:02:02 throw indexOutOfRange(this, 10);
Feb 04 22:02:02 ^
Feb 04 22:02:02 RangeError: index out of range: 16384 + 10 > 16384
Feb 04 22:02:02 at indexOutOfRange (/root/.gauge/plugins/js/2.3.7/node_modules/protobufjs/src/reader.js:13:12)
Feb 04 22:02:02 at BufferReader.read_uint32 [as uint32] (/root/.gauge/plugins/js/2.3.7/node_modules/protobufjs/src/reader.js:94:19)
Feb 04 22:02:02 at Type.StepInfo$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.7/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:8:11)
Feb 04 22:02:02 at Type.ExecutionInfo$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.7/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:17:26)
Feb 04 22:02:02 at Type.StepExecutionEndingRequest$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.7/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:11:35)
Feb 04 22:02:02 at Type.Message$decode [as decode] (eval at Codegen (/root/.gauge/plugins/js/2.3.7/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:35:41)
Feb 04 22:02:02 at Type.decodeDelimited (/root/.gauge/plugins/js/2.3.7/node_modules/protobufjs/src/type.js:520:17)
Feb 04 22:02:02 at Socket.messageHandler (/root/.gauge/plugins/js/2.3.7/src/connection.js:20:49)
Feb 04 22:02:02 at Socket.emit (events.js:193:13)
Feb 04 22:02:02 at addChunk (_stream_readable.js:295:12)
```

Does the code need to handle this exception in a better way?
https://github.com/getgauge/gauge-js/blob/master/src/connection.js#L19-L21

**Comment by Debashis9012** [comment] 2020-02-05 08:52
Could you please provide the sample project with steps to reproduce it will be easier for us to replicate the same issue?

**Comment by kramvan1** [comment] 2020-02-05 17:44
That won't be possible, this is deeply imbedded within our testing infra.
we do override a number of properties to try to overcome this issue, but may also be part of the cause:
```
#The path to the gauge reports directory. Should be either relative to the project directory or an absolute path
gauge_reports_dir = reports

#Set as false if gauge reports should not be overwritten on each execution. A new time-stamped directory will be created on each execution.
overwrite_reports = true

# Set to false to disable screenshots on failure in reports.
screenshot_on_failure = false

# The path to the gauge logs directory. Should be either relative to the project directory or an absolute path
logs_directory = logs

# Use multi processes instead of threads for parallel test execution
enable_multithreading = false

# Timeout in milliseconds for requests from runner when invoked for ide.
ide_request_timeout = 60000

# Timeout in milliseconds for making a connection to plugins.
plugin_connection_timeout = 120000

# Timeout in milliseconds for a plugin to stop after a kill message has been sent.
plugin_kill_timeout = 20000

# Timeout in milliseconds for making a connection to the language runner.
runner_connection_timeout = 60000

# Timeout in milliseconds for requests from the language runner.
runner_request_timeout = 20000
```
hopefully that will help.

**Comment by BugDiver** [comment] 2020-03-25 08:14
duplicate of #1533

**Closed** 2020-03-25 08:14 UTC
