### ISSUE TITLE
Failed to install plugin 'js' version 2.3.4. - On Windows  - node version 12

### ISSUE THREAD

**Issue by supraja-kr** [getgauge/gauge-js#202] opened 2019-05-10 11:52 UTC
gauge install js 
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\AppData\Local\Temp\gauge_temp1557488528409953500\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\AppData\Local\Temp\gauge_temp1557488528409953500\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
Failed to install plugin 'js' version 2.3.4.
Reason: exit status 1

**Comment by nehashri** [comment] 2019-05-10 11:59
@supraja-kr This seems to be a duplicate of https://github.com/getgauge/gauge-js/issues/199. Please try to install the nightly version of gauge-js to fix this. We will soon make a release of gauge-js to fix this, in the meantime you can install the nightly version of gauge-js.

**Closed** 2019-05-15 10:01 UTC
