### ISSUE TITLE
Custom screenshot not working

### ISSUE THREAD

**Issue by fadc80** [getgauge/gauge-js#142] opened 2018-04-26 11:29 UTC
**Expected behavior**

Custom screenshot code executed

**Actual behavior**

Default screenshot attached to `html-report` 

**Steps to replicate**

1. Create a new project
```
mkdir test && cd test && gauge init js
```
2. Copy [ops.png](https://user-images.githubusercontent.com/12335761/39302502-3c88ef12-4929-11e8-9ccd-14b8ba44caa6.png) (fake screenshot) to the `test` folder

2. Add the following `screenshotFn` implementation to `tests/step_implementation.js`
```javascript
var fs = require('fs');
gauge.screenshotFn = function () {
  return fs.readFileSync("ops.png", "base64").toString();
};
```
4. Change `specs/example.spec` to make it fail 

5. Check the generated `html-report`

If you prefer I've created the [gauge-js-custom-screenshot-test](https://github.com/fadc80/gauge-js-custom-screenshot-test) repository to reproduce this issue.
   
**Versions**

OS: Ubuntu 16.04 LTS
Node: v7.10.1 

Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins

html-report (4.0.3)
js (2.1.0)
screenshot (0.0.1)
xml-report (0.2.0)

**Comment by BugDiver** [comment] 2018-05-08 05:17
The fix should be available in nightly >= 08-05-2018

**Comment by sguptatw** [comment] 2018-05-08 07:01
The issue is still replicable 

**Steps to replicate**
* Same as the original issue

**Version**
```
Gauge version: 0.9.8.nightly-2018-05-01
Commit Hash: 765d3e7

Plugins
-------
js (2.3.0.nightly-2018-05-08)
```

**Comment by sguptatw** [comment] 2018-05-08 07:48
The issue of screenshots not being available on hooks in html-report is tracked here - https://github.com/getgauge/html-report/issues/172

The issue reported is fixed in
```
Gauge version: 0.9.8.nightly-2018-05-01
Commit Hash: 765d3e7

Plugins
-------
js (2.3.0.nightly-2018-05-08)
```

**Closed by sguptatw** 2018-05-08 07:48 UTC
Labels: ready
